apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lszu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0026-tenant/tkwch-fix-0075-0026-app/devfile-sample-lszu@sha256:ceb1948f6eff992ef61a10b40f192243440ea9710c9b7f8af5b7418e4b8a10c5
        name: my-nodejs
        resources: {}
status: {}
